lightninglabs/lndclient

lightning_client.go

Combining a few unrelated changes:
- Add start/end height to ListTransactions
- Add DecodePaymentRequest to lightning client
- Add payment request field to payment struct
Tested this locally with Faraday, which needs the new endpoint.

lightningclient: add decode payment request function + extra fields

---

lightning_client.go
router_client.go

Our current loop server itests use the lnd basic client for testing. Once we start to use the other subservers (wallet kit in accounting, utxo locker in coin selection) we will need to switchover our itests to use `LndServices`. This PR adds the functions required to make that switch with the current itest setup. I am looking to add itests in /lightninglabs/faraday/pull/61 following this pattern, so require these functions to mimic this setup.

client: add open channel and connect functions

---

go.mod
go.sum
lnd_services.go

To make it easy for users of the `lndclient` library to specify they want to wait for lnd to be synced to its chain backend before continuing with their client application, the boolean `BlockUntilChainSynced` can now be set to true when creating a new `GrpcLndServices`. The `NewLndServices` function will then block until lnd thinks it's fully synced.

lnd_services: Add option BlockUntilChainSynced to NewLndServices

---

go.mod
go.sum

Update pointer to final release of `lnd 0.11.0`. Next step is to tag master so that we have at least one tag that is safe to use.
Suggestions welcome for the tagging name scheme. If we need to add more calls to `lndclient` that already exist in lnd 0.11.0, we need a new tag. It could be something like`lndclient v0.11.0-1.0.0`, but that isn't compatible with our other versioning schemes.

build: bump to lnd v0.11.0-beta

---

lightning_client.go

This PR extends `LightningClient` interface with wrappers for `UpdateChanPolicy` and `GetChanInfo` to allow effective manipulation of channel edge routing policies.

lndclient: add UpdateChanPolicy and GetChanInfo

---

lightning_client.go

This PR adds a few fields to our existing response:
- Add htlcs to our invoices
- Add close height to close summary
- Add invoice add and settle index to invoices
All of these changes are in the existing lnd 0.11.1 release, so can be merged.

lndclient: add invoice htlcs and close height

---

lightning_client.go

As part of github.com/lightninglabs/lndmon/issues/57 , I am going to switchover lndmon to use the full set of lnd servcies (rather than just the basic client), since we will need to add `routerrpc` anyway for htlc stream, we might as well go all the way now. 
This PR adds all the functions/fields that lndmon will require to switchover to the full client. I have a WIP for lndmon [here](https://github.com/carlaKC/lndmon/tree/57-lndlcientswitchover) which is working with this set of changes.

lndclient: add all functions required for lndmon

---

.github/pull_request_template.md
.github/workflows/main.yml
Makefile
go.mod
go.sum
lightning_client.go
lnd_services.go
macaroon_pouch.go
macaroon_recipes.go
macaroon_recipes_test.go
testdata/permissions.json

Addresses the problem described in https://github.com/lightninglabs/loop/issues/299.
This PR adds two functionalities:
1. Allow one custom macaroon to be specified (by providing `CustomMacaroonPath` instead of `MacaroonDir` in `NewLndServices`) instead of needing to have all `lnd` macaroons in the same directory. This allows users to use the `admin.macaroon` or a custom baked one.
2. To make it easy to get a "macaroon recipe" for all required subservers, a new helper function `MacaroonRecipe` is added. This requires the `lnrpc.Lightning.ListPermissions` RPC which was only added in `lnd v0.11.1`.
**NOTE:** This PR is against the `lnd-11-1` branch as it requires a compile-time dependency to that version. This code can also be used with older `lnd` versions but then the `MacaroonRecipe` …

lnd 0.11.1: allow custom macaroon to be used instead of requiring all subserver macaroons

---

router_client.go

Required for github.com/lightninglabs/lndmon/issues/57

router: add subscribe htlc events to router client

---

go.mod
lightning_client.go
lnd_services.go
lnd_services_test.go

This PR adds an option to wait for lnd's wallet to be unlocked before lndclient returns, similar to what we have done waiting for the chain to sync. 

client: optionally wait for lnd to be unlocked

---

lightning_client.go

In order to be able to use the custom tlv records of the invoices, I've exposed them in the InvoiceHtlc struct.

Expose Htlc CustomRecords

---

go.mod
go.sum
lnd_services.go

This PR bumps the `lnd-12-0` branch to the final version of `lnd`.

mod: bump to final version of lnd v0.12.0

---

lnd_services.go

This PR changes `NodePubKey` type to `route.Vertex` as this is what most of our client APIs expect.

lndclient: change NodePubKey type to route.Vertex

---

chainnotifier_client.go
invoices_client.go
lightning_client.go
lnd_services.go
router_client.go
signer_client.go
versioner_client.go
walletkit_client.go

Add the option to overwrite our existing hard-set 30 second timeout for lndclient rpc calls.
There is an argument for making this a per-call option, but I think that it's reasonable to have the option to be able to override the default value for all calls? Adding this now doesn't exclude the option of coming back to add per-call timeouts if we want them. 

multi: add custom rpc timeout to lndclient

---

lnd_services.go

lndservices: use rpc timeout if nonzero

---

.github/workflows/main.yml
.golangci.yml
Makefile
chainnotifier_client.go
go.mod
invoices_client.go
lightning_client.go
signer_client.go
walletkit_client.go

Found while running itests for https://github.com/lightninglabs/faraday/pull/119.
We forgot to add the timeout to two of our subservers.
To avoid this in the future, we're adding a linter config and actually run the linter and unit tests during CI.

Subserver timeout fix, add Makefile, run unit tests on CI

---

lightning_client.go

Change AddInvoice method to avoid invoice rounding to sat by using the Invoice field ValueMsat instead.

lndclient: Use field ValueMsat in invoice to avoid rounding

---

lightning_client.go

Adds publicOnly/activeOnly parameters to ListChannels rpc call

lndclient: adds extra parameters to ListChannels

---

lnd_services.go
macaroon_recipes.go
router_client.go

Htlc interceptor has been in lnd since 0.11, so we can add this to master. 

router: add htlcinterceptor

---

go.mod
macaroon_service.go
macaroon_service_test.go

Add MacaroonService. Loop, Pool, Faraday and now Lit all need to spin up their own macaroon services and currently the logic is just duplicated in each repo. So this commit aims to consolidate all that logic into one place. 
With this commit, a caller can choose to encrypt their macaroon.db file with a password of their choosing _or_ they can specify that instead a shared key should be derived with LND which will then be used to encrypt the db.

macaroon_service: add MacaroonService

---

README.md
go.mod
go.sum
lightning_client.go
lnd_services.go

Bump lnd's version to v0.14.2-beta to include the closing txid from waiting close channel response.

lndclient: add closing txid for waiting close channel response

---

README.md

Made the mistake to publish the `v0.14.2-1` without rebasing the changes last week. And apparently republishing the same tag did not update [the go library cache](https://pkg.go.dev/github.com/lightninglabs/lndclient@v0.14.2-1). Lessons learned.
Now we need to update the tag to include the rebase.
We may do a [module retraction](https://golangtutorial.dev/tips/retract-go-module-versions/) once we start to use go version >= 1.16.

lndclient: update tag version

---

router_client.go

This PR surfaces the `force` flag when importing MC pair history. When `force` is set, the pairs will overwrite the MC state regardless of freshness.
~- [ ] Version compatibility matrix in the README and minimal required version
in `lnd_services.go` are updated.~
~- [ ] Update `macaroon_recipes.go` if your PR adds a new method that is called
differently than the RPC method it invokes.~

router: support forced MC import

---

lightning_client.go
lightning_client_test.go

This PR modifies `lightningClient.AddInvoice` to pass along `DescriptionHash` to the underlying `lnrpc.LightningClient` `AddInvoice` call, as it was previously missing.
For example, previously the behaviour was:
```go
// client is lndclient.LightningClient
_, invStr, _ := client.AddInvoice(ctx, invoicesrpc.AddInvoiceData{
DescriptionHash: hashedDesc,
Value: lnwire.MilliSatoshi(100000),
})
decoded, _ := zpay32.Decode(bolt11, chainParams)
// Prints ""
fmt.Printf("%q", decoded.Description)
// Prints nil
fmt.Printf("%v", decoded.DescriptionHash)
```
I didn't add any of the other fields that are _**also**_ not currently passed along from the [AddInvoiceData](https://pkg.go.dev/github.com/lightningnetwork/lnd/lnrpc/invoicesrpc@v0.14.3-beta#AddInvoiceData) to the …

Include invoice description hash when adding invoice via RPC client

---

router_client.go
testdata/permissions.json

Unfortunately I didn't add UpdateChanStatus to the router interface in the last commit.
I tested the rpc call with a local running lnd 0.15.0.

router_client: add UpdateChanStatus to router interface

---

go.mod
go.sum
macaroon_service.go
macaroon_service_test.go
testdata/permissions.json
walletkit_client.go

In this commit we update to the new version of the macaroons package
that doesn't require the caller to use the default implementation for
the root key store. Instead, the caller can pass in an implementation,
and based on that we'll change our behavior.

macaroons: update to new macaroons pkg version

---

go.mod
go.sum
lightning_client.go

In this commit, we update the RegisterRPCMiddleware function to wait for
the server to indicate that it has completed registering the middleware
interceptor before returning from the function. This allows clients to
register mw clients in a deterministic order.
Depends on https://github.com/lightningnetwork/lnd/pull/6754
Not familiar with how branches are organised in this repo. So not sure if this is opened against the correct branch?

multi: wait for rpc MW registration complete msg

---

lightning_client.go

This is a minor PR that introduces the `chan_status_flags` field of lnd API's [channels](https://api.lightning.community/#lnrpc-channel) to `lndclient`'s `ChannelInfo`.

lndclient: include chan status flags on listchannels

---

chainnotifier_client.go
go.mod
go.sum
tx_utils.go

In order to not break all the other callers, we opt to more or less copy
over the functional options added on the lnd side of things. We would be
able to just use the existing opts, but the includeBlock field is
private (as it should be imo).

lndclient: expose new option to recv the block w/ a conf ntfn

---

lightning_client.go
lnd_services.go

Make lndclient zeroconf ready
in `lnd_services.go` are updated. <= only after merging to master?

multi: propagate zero conf fields to the `ChannelAcceptResponse`

---

chainnotifier_client.go
go.mod
go.sum
lightning_client.go
lnd_services.go
testdata/permissions.json
walletkit_client.go

~Depends on https://github.com/lightninglabs/lndclient/pull/113 and https://github.com/lightningnetwork/lnd/pull/6775.~
Adds the new `ImportTaprootScript` RPC of the `WalletKit` subserver.

walletkit: add ImportTaprootScript RPC

---

lightning_client.go

Adds the ability to attach funding shims to open channel requests. It is introduced as an optional argument.

lndclient: add WithFundingShim opt to openchannel

---

lightning_client.go

Adds another optional argument to the `OpenChannel` function which enables specifying a commitment type to be used on the channel.

lndclient: add commitment type option to openchannel

---

lightning_client.go

Adds an optional argument to `OpenChannel` to support scid channel opens.

lndclient: add scid opt to openchannel

---

lightning_client.go
macaroon_recipes.go

Adds a new method for asynchronous `OpenChannel`. It returns the grpc stream for the `lndclient` user to listen to updates.

lndclient: add openchannel async call

---

lightning_client.go

Minor hotfix PR for previous `OpenChannelStream` merge. The context used did not carry the required macaroon for the RPC call to succeed.

hotfix/lndclient: add macaroon context to OpenChannelStream

---

lightning_client.go

This commit fixes a bug where the in-correct context's error message is returned resulting in a nil error being returned when the context is canceled. On a middleware registration error, the first thing we will pick up here is that the context is cancelled, however, this does not provide the user with much feedback about what went wrong and so an additional log statement is also added on the stream's Recv func as this will provide the user with more info.

lightning-client: return correct context error

---

lnd_services.go
macaroon_pouch.go

This commit removes the unneded chainkit.macaroon dependency as the chainkit RPC service currently uses the chainnoitifer.macaroon.

chainkit: fix macaroon

---

macaroon_service.go
macaroon_service_test.go

When using the default `BoltMacaroonStore` as root key store we may want to close the BoltDB instance correctly to avoid it holding the macaroon database file until the instance is properly GCd. This commit makes this possible by returning the `kvdb` backend instance so callers can make sure to close it properly.

macaroons: Bolt macaroon store fix

---

lightning_client.go

Previously, the interceptStream's context was listened on for any context cancelation. However, this is not required since if the interceptStream's context is canceled then the `Recv()` method would also return a "context canceled" error which would be put into the `errChan` which is then listened on. If we listen on both the ctx.Done() channel and the error channel then the ctx channel will always fire first which results in a less meaningful error being returned.

lightning: fix RegisterRPCMiddleware error handling

---

lightning_client.go
router_client.go

An AMP invoice does not have an invoice-level preimage. Each htlc part of an AMP payment has its own hash/preimage pair.
This was blocking my litd from starting up. The account service subscribes to the invoice stream and without this changes lndclient will return an error when it is not able to parse the preimage for a settled invoice.
```
2023-05-29 19:20:24.075 [ERR] ACCT: Error in invoice subscription: invalid preimage length of 0, want 32
```

multi: hanlde empty invoice preimages for AMP invocies

---

chainkit_client.go
go.mod
go.sum
testdata/permissions.json

Only bumping the lnd version to `v0.17.1-beta.rc1` and exposing the `GetBlockHeader` call.
IIUC this should go in a new branch, not master.

mod+lightning+chainkit: update to lnd v0.17.1-beta.rc1 and expose GetBlockHeader

---

go.mod
go.sum

Bumping the lnd version now that 0.17.1 is out of RC.

mod+lightning: update to lnd v0.17.1-beta final

---

lightning_client.go
macaroon_recipes_test.go

added support for the main RPC implementation of message signing.

client: implemented messaging signing.

---

lightning_client.go
macaroon_recipes_test.go

added support for the main RPC message verification API endpoint.

feat: implemented main rpc signature verification

---

lnd_services.go

This is a temporary workaround for https://github.com/lightninglabs/faraday/issues/177.
We should start paginating certain calls to `lnd` in our projects, seems like the `GetTransactions` call would be the most urgent candidate.

lnd_services: increase client gRPC max receive size

---

router_client.go

This PR expands the InterceptHtlc func by adding the two remaining fields CustomRecords and OnionBlob to the InterceptedHtlc struct

routerclient: expand InterceptHtlc func

---

lnd_services.go

Add the `state` RPC client to the list of exported LND services. This may be useful in assessing health of `lnd` instances from the payment service's health checking routines.

lndclient: add rpc/daemon state client to services

---

lightning_client.go

This PR adds an optional argument to the open channel request for the remote reserve amount.

Add openchannel reserve option

---

lightning_client.go

lndclient: add inbound fee support to the lightning client

---

chainkit_client.go
chainnotifier_client.go
invoices_client.go
lightning_client.go
lnd_services.go
lnd_services_test.go
macaroon_recipes.go
router_client.go
signer_client.go
state_client.go
versioner_client.go
walletkit_client.go

This allows us to use the underlying RPC methods directly while still taking advantage of the macaroon management.
Using the raw RPC methods directly can be useful when a new method isn't implemented in `lndclient` yet or when we want to pass the raw RPC request method directly instead of converting it to the `lndclient` structs.

Add `RawClientWithMacAuth` to each client

---

lnd_services.go

References:
- https://github.com/lightninglabs/faraday/issues/177
- https://github.com/lightninglabs/faraday/pull/195
- https://github.com/lightninglabs/faraday/pull/178
The faraday rpcclient was maxrecvsize was [updated](https://github.com/lightninglabs/faraday/blob/master/frdrpcserver/rpcserver.go#L60), but we're still running into this issue:
```
{'code': 8, 'message': 'grpc: received message larger than max (419942095 vs. 419430400)', 'details': []}
```
I think we'll also need to update the lndclient maxrecvsize?  Similar to the PR [here](https://github.com/lightninglabs/faraday/pull/195), this updates the grpc max recv size to match the faraday service.
Temporary fix for bumping the memory up a little as this allows us to work with nodes that have large amount of data.  Once this is …

Update lndclient grpc max recv size

---

invoices_client.go

Before this commit, callers wouldn't be able to use an msat amount as input to the hold invoice RPC call. Instead, the wrapper logic would always convert to msat first, causing a loss in precision. For most cases, sat amounts are fine, but some use cases require higher precision.
We fix this by keeping the input value in mSat (as typed), while using the `ValueMsat` field as `lnd` would expect.

invoiecs: fix value conversion bug in AddHodlInvoice

---

lightning_client.go

`CustomRecords` were introduced in v0.16.0, which is why master is selected as the base branch

lndclient: pass custom records into RoutingPolicy

---

macaroon_recipes.go
walletkit_client.go

Added MinRelayFee func to walletkit_client.go.

Minrelayfee func

---

invoices_client.go

Previously we'd only pass through a very limited set of the parameters to the LND RPC, and we'd hard-code certain values like `Private: true`.
With this PR we're forwarding the request as it was given to lndclient, without changing any of its body.

Expose all params for `AddHoldInvoice`

---

lnd_services.go

- Related to this PR:  https://github.com/lightninglabs/faraday/pull/201
```
Exception: Unexpected response from Faraday API: {'code': 8, 'message': 'grpc: received message larger than max (630803848 vs. 629145600)', 'details': []}
```
The gRPC message size limit is being increased to 800 MiB to accommodate large payloads generated by specific use cases, such as transaction histories or detailed audit reports. Trying to strike a balance between supporting current operational needs and maintaining resource efficiency.

lndclient: update lndclient grpc max recv size

---

lnd_services.go
walletkit_client.go

Use new fields instead of deprecated
'force' -> 'immediate'
'sat_per_byte' -> 'sat_per_vbyte'
New options added: 'immediate', 'target_conf', 'budget'.

bumpfee: add more flags as options 

---

lightning_client.go
lightning_client_test.go

Previously we'd always pass Private=true.
Fix https://github.com/lightninglabs/lndclient/issues/207

AddInvoice: expose field Private

---

signer_client.go

signer: option to add the local nonce to the MuSig2 session

---

lightning_client.go

Adds ~the NoWait flag~ functional options to `CloseChannel`.

closechannel: add functional options

---

signer_client.go

Previously if the `keyLocaltor` argument was unset `DeriveSharedKey` would crash.

signer: allow passing nil keyLocator to DeriveSharedKey

---

lightning_client.go
lnd_services_test.go

Add fields: CommitHash, BestBlockHash, Color, NumPeers.

GetInfo: add more fields to response

---

chainnotifier_client.go

lndclient: make notifier options exported (to help mocking)

---

chainnotifier_client.go

The corresponding API of LND already supports notifying the caller about a reorg. I reused NotifierOption's used for RegisterConfirmationsNtfn already to pass a channel notified upon a reorg affecting a reported confirmation.

RegisterSpendNtfn: support reorg channel

---

.golangci.yml
Makefile
chainkit_client.go
chainnotifier_client.go
lightning_client.go
macaroon_pouch.go
macaroon_service.go
signer_client.go
walletkit_client.go

We enable linter caching, enable and fix the long line linter (https://github.com/lightningnetwork/lnd/blob/master/docs/development_guidelines.md#80-character-line-length) as well as add some rules concerning exported symbols (https://github.com/lightningnetwork/lnd/blob/master/docs/development_guidelines.md#code-documentation-and-commenting).

linter: enforce some constraints from code guidelines

---

lnd_services.go
macaroon_recipes.go
wtclient_client.go

This PR adds the WatchtowerClient interface. The reason for adding this is so that it can be used in `lndmon` in a way described here: https://github.com/lightninglabs/lndmon/issues/118

Add WatchtowerClient interface
