lightninglabs/lndclient

signer_client.go
Some projects contain code to set this field, while it is actually unused. This PR removes the field.
=> add SignDescriptor struct without unused SigHashes field

lightning_client.go
This would help users to build solutions to work with channel backup snapshots.
It adds a function to `lndclient` to subscribe to new channel backups.
=> lndclient: add subscribe channel backups to client

lightning_client.go
This PR makes it possible to connect to a peer permanently.
=> lndclient: add permanent flag to Connect

lightning_client.go
As I mentioned in #24 SubscribeInvoices was missing from LightningClient.
I tried my best to match the existing base code.
Let me know how I can improve this.
=> lndclient: add SubscribeInvoices

lightning_client.go
The `DescribeGraph` call returned nodes without the pubkeys. This PR fixes this by extending `lndclient.Node` with a `PubKey` member.
=> lndclient: add pubkey to Node

go.mod, go.sum, lightning_client.go, macaroon_recipes.go
Note: first commit to be updated once LND master is tagged.
=> lndclient: use Features map instead the deprecated GlobalFeatures in the NodeUpdate

.github/pull_request_template.md, README.md
We add a README that explains how the version compatibility and
branching strategy work.
=> README: describe version matrix and branching strategy

lightning_client.go, macaroon_recipes.go
in `lnd_services.go` are updated. (Not needed)
=> lndclient: guard against hidden decode error when GlobalFeatures is nil

lightning_client.go
~- [x] Version compatibility matrix in the README and minimal required version
in `lnd_services.go` are updated.~
=> lndclient: ChanInfo to include pending htlc values and direction

router_client.go
=> router: add EstimeRouteFee

router_client.go
=> router: add htlc attempt detail to trackpayment

.github/pull_request_template.md, Makefile, README.md, go.mod, go.sum, lightning_client.go, lnd_services.go, macaroon_recipes.go, macaroon_recipes_test.go, testdata/permissions.json
=> Merge lnd-11-1 branch to master (bump required min version of lnd to v0.11.1-beta)

lnd_services.go
The new version 0.13 of lnd doesn't return the same RPC error codes
anymore if its wallet is still locked. We need to do some string
matching here to avoid needing to pull in the 0.13 version as a
dependency which would nullify our efforts to have backward compatible
branches of lndclient.
=> lnd_services: make unlock wait compatible with lnd 0.13

lightning_client.go
~- [ ] Version compatibility matrix in the README and minimal required version
in `lnd_services.go` are updated.~
~- [ ] Update `macaroon_recipes.go` if your PR adds a new method that is called
differently than the RPC method it invokes.~
=> lndclient: add (incomplete) QueryRoutes

router_client.go
=> router: add msat fee limit for SendPayment

invoices_client.go
lightningnetwork/lnd/pull/5207 terminates our single invoice stream once a final state has been delivered to the stream, which results in an `EOF` being sent to the client. This PR updates `SubscribeSingleInvoice` to handle the EOF is the same way that we do for `TrackPayment`, closing the update channel to indicate that we're done sending updates.
Although this functionality is not in lnd 0.11 (the version on our master branch of lndclient), I've opened this against master so that master properly works with 0.13.
=> invoices: handle EOF from subscribe single invoice

lightning_client.go
=> lightning: add upfront shutdown address to channel info

lightning_client.go
=> multi: add additional information to pending htlcs 

testdata/permissions.json, walletkit_client.go
=> Wallet list accounts

README.md, go.mod, go.sum, lnd_services.go
This PR is opened against the `lnd-14-0` branch.
=> lnd-14: bump to lnd v0.14.0-beta.rc1

macaroon_recipes.go, router_client.go, testdata/permissions.json
- [x ] PR is opened against correct version branch.
=> Add Mission Control import, query and reset

lnd_services.go, lnd_services_test.go
=> lnd_services: export AssertVersionCompatible

lightning_client.go
=> lndclient: Add chan event for ChannelEventUpdate_FULLY_RESOLVED_CHANNEL

lightning_client.go, macaroon_recipes.go
=> client: add a more generic `EstimateFee` and remove `EstimateFeeP2WSH`

macaroon_recipes.go, walletkit_client.go
=> walletkit: rename EstimateFee to avoid collision

walletkit_client.go
=> walletkit_client: add fields to NextAddr

router_client.go
This PR adds the UpdateChanStatus method from routerrpc method to the router_client.
=> router_client: add UpdateChannelStatus method

go.mod, go.sum, signer_client.go
=> mod+signer_client: add Schnorr signing and verifying

signer_client.go
To be able to correctly sign transactions that have taproot inputs we need to also pass the previous outs to `ComputeInputScript`. This PR addresses this missing functionality.
=> signer: add prev outs to ComputeInputScript

lightning_client.go
=> Add  zero conf arg to OpenChannel

lightning_client.go
Adds a new wrapper for the LND RPC call [`FundingStateStep`](https://api.lightning.community/#fundingstatestep) as a method to `LightningClient`.
=> lndclient: add FundingStateStep call

lightning_client.go
This PR adds more detail to the pending channels. Local and remote balances and force close maturity, anchor state, limbo and recovered balances.
=> client: add more detail to the pending channels

lightning_client.go
=> Add zeroconf and scids to `ChannelInfo`

chainnotifier_client.go
With this commit we add the WithReOrgChan functional option to the RegisterConfirmationsNtfn method that allows a caller to be notified about a chain re-organization of a transaction.
Using WithReOrgChan() might be a breaking change to the caller, as the behavior of the RegisterConfirmationsNtfn changes: Before, the notification channel would not continue sending updates after a confirmation event was received. When enabling WithReOrgChan(), the notification channel will continue sending updates even after a first confirmation, and will also send on the provided re-org channel if a re-org happens. After a re-org a new confirmation event is sent on the notification channel once the transaction is included in another block again.
To allow a caller to reliably make sure a transaction reaches …
=> chainnotifier: add re-org chan option to RegisterConfirmationsNtfn

router_client.go
=> lndclient: add TimePref to SendPaymentRequest

lnd_services.go, network.go
=> Add testnet4 support
